### ISSUE TITLE
Add custom user as a module variable; provision with rendered cloud-init and user_data

### ISSUE THREAD

**Issue by kpeder** [pythian/tf_aws_bastion#4]
Need to add the ability to create a custom initial user on the bastion.

Use a cloud-init.tpl file, and render the configuration using data template file from a new user variable.

This variable should be optional; if not specified, nothing should break.

Create an output for this user as well, this can be pulled from the remote state file for reference.

**Comment by pythianlazam** [comment]
Created [PR#5.](https://github.com/pythian/tf_aws_bastion/pull/5)

**Comment by alcher** [comment]
Closed
